# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 08:08
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pipeline.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('public_id', models.CharField(default=pipeline.utils.generate_random_id, max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('bitrate', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='pipeline.Video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSubtitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=pipeline.utils.generate_random_id, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('language', models.CharField(choices=[(b'af', b'Afrikaans'), (b'ar', b'Arabic'), (b'az', b'Azerbaijani'), (b'bg', b'Bulgarian'), (b'be', b'Belarusian'), (b'bn', b'Bengali'), (b'br', b'Breton'), (b'bs', b'Bosnian'), (b'ca', b'Catalan'), (b'cs', b'Czech'), (b'cy', b'Welsh'), (b'da', b'Danish'), (b'de', b'German'), (b'el', b'Greek'), (b'en', b'English'), (b'eo', b'Esperanto'), (b'es', b'Spanish'), (b'et', b'Estonian'), (b'eu', b'Basque'), (b'fa', b'Persian'), (b'fi', b'Finnish'), (b'fr', b'French'), (b'fy', b'Frisian'), (b'ga', b'Irish'), (b'gd', b'Scottish Gaelic'), (b'gl', b'Galician'), (b'he', b'Hebrew'), (b'hi', b'Hindi'), (b'hr', b'Croatian'), (b'hu', b'Hungarian'), (b'ia', b'Interlingua'), (b'id', b'Indonesian'), (b'io', b'Ido'), (b'is', b'Icelandic'), (b'it', b'Italian'), (b'ja', b'Japanese'), (b'ka', b'Georgian'), (b'kk', b'Kazakh'), (b'km', b'Khmer'), (b'kn', b'Kannada'), (b'ko', b'Korean'), (b'lb', b'Luxembourgish'), (b'lt', b'Lithuanian'), (b'lv', b'Latvian'), (b'mk', b'Macedonian'), (b'ml', b'Malayalam'), (b'mn', b'Mongolian'), (b'mr', b'Marathi'), (b'my', b'Burmese'), (b'nb', b'Norwegian Bokmal'), (b'ne', b'Nepali'), (b'nl', b'Dutch'), (b'nn', b'Norwegian Nynorsk'), (b'os', b'Ossetic'), (b'pa', b'Punjabi'), (b'pl', b'Polish'), (b'pt', b'Portuguese'), (b'ro', b'Romanian'), (b'ru', b'Russian'), (b'sk', b'Slovak'), (b'sl', b'Slovenian'), (b'sq', b'Albanian'), (b'sr', b'Serbian'), (b'sv', b'Swedish'), (b'sw', b'Swahili'), (b'ta', b'Tamil'), (b'te', b'Telugu'), (b'th', b'Thai'), (b'tr', b'Turkish'), (b'tt', b'Tatar'), (b'uk', b'Ukrainian'), (b'ur', b'Urdu'), (b'vi', b'Vietnamese')], max_length=2, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='pipeline.Video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoTranscoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now=True, verbose_name=b'Time of transcoding job start')),
                ('progress', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name=b'Progress percentage')),
                ('status', models.CharField(choices=[(b'pending', b'Pending'), (b'processing', b'Processing'), (b'failed', b'Failed'), (b'success', b'Success')], max_length=32, verbose_name=b'Status')),
                ('message', models.CharField(blank=True, max_length=1024)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcoding', to='pipeline.Video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoUploadUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_video_id', models.CharField(default=pipeline.utils.generate_random_id, max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('filename', models.CharField(max_length=128, verbose_name=b'Uploaded file name')),
                ('expires_at', models.IntegerField(db_index=True, verbose_name=b'Timestamp at which the url expires')),
                ('was_used', models.BooleanField(db_index=True, default=False, verbose_name=b'Was the upload url used?')),
                ('last_checked', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name=b'Last time it was checked if the url was used')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_upload_urls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
