# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotranscoding',
            name='message',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
