# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videouploadurl',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.Playlist', verbose_name='Playlist to which the video will be added after upload'),
        ),
    ]
