# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 12:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_auto_20160809_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoformat',
            name='bitrate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videoformat',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='pipeline.Video'),
        ),
    ]
