# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-05 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pipeline", "0005_auto_20160825_0819")]

    operations = [
        migrations.AlterField(
            model_name="processingstate",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("failed", "Failed"),
                    ("success", "Success"),
                    ("restart", "Restart"),
                ],
                default="pending",
                max_length=32,
                verbose_name="Status",
            ),
        )
    ]
