# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("pipeline", "0006_auto_20160905_1245")]

    operations = [
        migrations.RemoveField(model_name="videouploadurl", name="filename"),
        migrations.RemoveField(model_name="videouploadurl", name="last_checked"),
    ]
