# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-13 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_auto_20160913_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='videouploadurl',
            name='origin',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Access-Control-Allow-Origin header value to add to CORS responses'),
        ),
    ]
