# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 09:54
from __future__ import unicode_literals

from django.db import migrations

import pipeline.backend
import pipeline.utils


def create_thumbnails(apps, schema_editor):
    Video = apps.get_model("pipeline", "Video")
    backend = pipeline.backend.get()
    for video in Video.objects.all():
        try:
            # Create new thumbnail id
            video.public_thumbnail_id = pipeline.utils.generate_long_random_id()
            video.save()

            # Create thumbnail
            backend.create_thumbnail(video.public_id, video.public_thumbnail_id)
        except NotImplementedError:
            pass

def delete_thumbnails(apps, schema_editor):
    Video = apps.get_model("pipeline", "Video")
    backend = pipeline.backend.get()
    for video in Video.objects.all():
        try:
            backend.delete_thumbnail(video.public_id, video.public_thumbnail_id)
        except NotImplementedError:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0010_video_public_thumbnail_id'),
    ]

    operations = [
        migrations.RunPython(create_thumbnails, reverse_code=delete_thumbnails),
    ]
