# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 10:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models

import pipeline.utils


class Migration(migrations.Migration):

    dependencies = [("pipeline", "0011_create_thumbnails")]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="public_thumbnail_id",
            field=models.CharField(
                default=pipeline.utils.generate_long_random_id,
                max_length=20,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(20)],
            ),
        )
    ]
