# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-02 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django_auth_lti.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LTIOauthCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('secret', models.CharField(default=django_auth_lti.models.generate_strong_secret, max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('org_name', models.CharField(max_length=255)),
                ('org_contact_email', models.EmailField(max_length=254)),
                ('org_contact_firstname', models.CharField(max_length=255)),
                ('org_contact_lastname', models.CharField(max_length=255)),
            ],
        ),
    ]
