# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-02 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_lti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lticourseuser',
            name='roles',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Roles'),
        ),
    ]
