# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-02 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0014_auto_20180702_0947'),
        ('django_app_lti', '0002_auto_20180702_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiresource',
            name='playlists',
            field=models.ManyToManyField(to='pipeline.Playlist'),
        ),
    ]
